$(document).ready(function(){
    $.ajax({
        url:"https://en.wikipedia.org/wiki/High_School_DxD",
        headers:{
            "Access-Control-Allow-Origin":"*"
        },
        success:function(){
            console.log("success");
        },
        error:function(){
            console.log("error");
        }
    })
})
